resolver: lts-16.12

packages:
- .

nix:
    enable: true
    packages: [llvm_9]

extra-deps:
- unbound-generics-0.4.1@sha256:5020e8397dad610846cbd5bdc855e20edf9b9cb74f93f6c09488bba21118c409,5485

# Override default flag values for local packages and extra-deps
# flags: {}

# Extra package databases containing global packages
# extra-package-dbs: []
